// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtokentest.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the JSONWebTokenTest module

	public static java.lang.String getSecret()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("JSONWebTokenTest.Secret");
	}
}