// This file was generated by Mendix Modeler 6.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtokentest.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the JSONWebTokenTest module

	public static String getSecret()
	{
		return (String)Core.getConfiguration().getConstantValue("JSONWebTokenTest.Secret");
	}
}