// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtoken.proxies;

public class ArrayValue
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject arrayValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "JSONWebToken.ArrayValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		ArrayValue_Claim("JSONWebToken.ArrayValue_Claim");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ArrayValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "JSONWebToken.ArrayValue"));
	}

	protected ArrayValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject arrayValueMendixObject)
	{
		if (arrayValueMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("JSONWebToken.ArrayValue", arrayValueMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a JSONWebToken.ArrayValue");

		this.arrayValueMendixObject = arrayValueMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ArrayValue.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static jsonwebtoken.proxies.ArrayValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return jsonwebtoken.proxies.ArrayValue.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static jsonwebtoken.proxies.ArrayValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new jsonwebtoken.proxies.ArrayValue(context, mendixObject);
	}

	public static jsonwebtoken.proxies.ArrayValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return jsonwebtoken.proxies.ArrayValue.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value
	 */
	public final String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of ArrayValue_Claim
	 */
	public final jsonwebtoken.proxies.Claim getArrayValue_Claim() throws com.mendix.core.CoreException
	{
		return getArrayValue_Claim(getContext());
	}

	/**
	 * @param context
	 * @return value of ArrayValue_Claim
	 */
	public final jsonwebtoken.proxies.Claim getArrayValue_Claim(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		jsonwebtoken.proxies.Claim result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ArrayValue_Claim.toString());
		if (identifier != null)
			result = jsonwebtoken.proxies.Claim.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ArrayValue_Claim
	 * @param arrayvalue_claim
	 */
	public final void setArrayValue_Claim(jsonwebtoken.proxies.Claim arrayvalue_claim)
	{
		setArrayValue_Claim(getContext(), arrayvalue_claim);
	}

	/**
	 * Set value of ArrayValue_Claim
	 * @param context
	 * @param arrayvalue_claim
	 */
	public final void setArrayValue_Claim(com.mendix.systemwideinterfaces.core.IContext context, jsonwebtoken.proxies.Claim arrayvalue_claim)
	{
		if (arrayvalue_claim == null)
			getMendixObject().setValue(context, MemberNames.ArrayValue_Claim.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ArrayValue_Claim.toString(), arrayvalue_claim.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return arrayValueMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final jsonwebtoken.proxies.ArrayValue that = (jsonwebtoken.proxies.ArrayValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "JSONWebToken.ArrayValue";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
