// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtoken.proxies;

public enum Enum_ClaimValueType
{
	String(new String[][] { new String[] { "en_US", "String" } }),
	Integer(new String[][] { new String[] { "en_US", "Integer" } }),
	Array(new String[][] { new String[] { "en_US", "Array" } });

	private java.util.Map<String,String> captions;

	private Enum_ClaimValueType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
