// This file was generated by Mendix Modeler 6.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonwebtokentest.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the JSONWebTokenTest module
	public static boolean aSt_AfterStartup(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (Boolean)Core.execute(context, "JSONWebTokenTest.ASt_AfterStartup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void dL_JWT_VerifyTokenResult(IContext context, String _token)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Token", _token);
			Core.execute(context, "JSONWebTokenTest.DL_JWT_VerifyTokenResult", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_VerifyToken_Decode(IContext context, jsonwebtokentest.proxies.VerifyToken _verifyToken)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("VerifyToken", _verifyToken == null ? null : _verifyToken.getMendixObject());
			Core.execute(context, "JSONWebTokenTest.MB_VerifyToken_Decode", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_VerifyToken_GetSingleClaim(IContext context, jsonwebtokentest.proxies.VerifyToken _verifyToken)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("VerifyToken", _verifyToken == null ? null : _verifyToken.getMendixObject());
			Core.execute(context, "JSONWebTokenTest.MB_VerifyToken_GetSingleClaim", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_VerifyToken_New(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "JSONWebTokenTest.MB_VerifyToken_New", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_VerifyToken_Verify(IContext context, jsonwebtokentest.proxies.VerifyToken _verifyToken)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("VerifyToken", _verifyToken == null ? null : _verifyToken.getMendixObject());
			Core.execute(context, "JSONWebTokenTest.MB_VerifyToken_Verify", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}